### ISSUE TITLE
Record type is {}

### ISSUE THREAD

**Issue by Cristuker** [bluesky-social/atproto#2781] opened 2024-09-03 12:36 UTC
Well I'm using this in my node.js bot and when I use the bot types from listConvos() I receive this type

```
export interface Notification {
  uri: string
  cid: string
  author: AppBskyActorDefs.ProfileView
  /** Expected values are 'like', 'repost', 'follow', 'mention', 'reply', 'quote', and 'starterpack-joined'. */
  reason:
    | 'like'
    | 'repost'
    | 'follow'
    | 'mention'
    | 'reply'
    | 'quote'
    | 'starterpack-joined'
    | (string & {})
  reasonSubject?: string
  record: {}
  isRead: boolean
  indexedAt: string
  labels?: ComAtprotoLabelDefs.Label[]
  [k: string]: unknown
}
```
 Record is a empty object. But when I run the code I receive other kinda of object

```
"record": {
      "$type": "app.bsky.feed.post",
      "createdAt": "2024-09-02T15:50:54.148Z",
      "facets": [
        {
          "$type": "app.bsky.richtext.facet",
          "features": [
            {
              "$type": "app.bsky.richtext.facet#mention",
              "did": "did:plc:ycisingvth7pg3w22c6amin6"
            }
          ],
          "index": {
            "byteEnd": 23,
            "byteStart": 0
          }
        }
      ],
```
and record has properties

**To Reproduce**

1. agent.ListConvos()
2. Print the object

**Expected behavior**

The type system represent the object that returns
**Details**

- Operating system: Linux
- Node version: 18

**Additional context**

-

**Comment by mary-ext** [comment] 2024-09-04 23:50
Intentional, duplicate of https://github.com/bluesky-social/atproto/issues/999

**Closed** 2024-09-09 18:46 UTC
Labels: bug
